Feature/hu2008 footer
dr-von-doom/exclusive pull request #12
Opened 2024-09-19 03:42 UTC by EmilyRoldan

2024-09-20 12:58 UTC, Orun1tia approved these changes

2024-09-20 19:58 UTC, Sonya-c requested changes
Muy bien hecho! Hay un par de cositas por mejorar aquí y allá en el código. Visualmente, creo que estaría bien si la parte superior del footer (la que contiene los logos) tenga el mismo espaciado que tiene la parte inferior. Además, creo que (al menos en escritorio) se puede aumentar el espacio entre los logos (los veo algo juntos). 

![image](https://github.com/user-attachments/assets/51cd2556-8022-4f75-b5b3-6a8b217d3ae0)

La versión movil se ve muy bien

2024-09-20 19:58 UTC, Sonya-c commented on src/components/Footer/Footer.tsx
> +          </ul>
Esto si lo tienes que sacar de los datos

2024-09-20 19:58 UTC, Sonya-c commented on src/components/Footer/Footer.tsx
> +    <footer className="bg-black p-5 font-inter text-sm text-white">
Ya que inter es la fuente por defecto, podrías aplicarla en el css

2024-09-20 19:58 UTC, Sonya-c commented on src/components/Footer/Footer.tsx
> +          </form>
Si el botton va a hacer de tipo submmit, por defecto el formulario va a redireccionar a otra pagina. Es necesario crear un handler 

En el boton hay que añadir una acción en el submmit


```
<form onSubmit={this.handleSubmmit}>
```

Y luego prevenimos el comportamiento por defecto de esta forma usando `preventDefault`

```
const handleSubmmit = (event) => {
  event.preventDefault();
}
```

2024-09-21 21:44 UTC, Orun1tia approved these changes

2024-09-21 23:24 UTC, Sonya-c commented
Buen trabajo!

2024-09-21 23:24 UTC, Sonya-c approved these changes

2024-09-22 03:14 UTC, merged