Featured products completed
dr-von-doom/exclusive pull request #14
Opened 2024-09-19 13:54 UTC by daolivaress

2024-09-19 17:00 UTC, octavio-delahoz-uninorte commented on src/services/featured-product-service.ts
> +export const getFeaturedProducts = (): Product[] => {
Hola, donde utilizas esto ? Si no se está usando en ninguna parte, por favor eliminar.

2024-09-19 17:07 UTC, daolivaress commented on src/services/featured-product-service.ts
> +export const getFeaturedProducts = (): Product[] => {
Ya implemente el servicio para obtener los datos, el primer pr fue una prueba sin usarlos profe

2024-09-19 17:25 UTC, octavio-delahoz-uninorte commented on src/components/Product/FeaturedProductView/FeaturedProductView.tsx
> +  useEffect(() => {
Esto no sería necesario ahora, puedes importar solamente el array de productos, con eso es suficiente. Cuando implementemos api lo vamos hacer con tanstack-query y tiene una lógica totalmente diferente. Es decir, esta porción de código, tendrías que eliminarla más adelante.

2024-09-19 17:28 UTC, octavio-delahoz-uninorte commented on src/services/featured-product-service.ts
> +export const getFeaturedProducts = (): Product[] => {
El service si lo vamos a implementar después cuando hagamos fetch de api. Pero para este sprint no se necesita. Por favor no agreguemos código adicional que no se vaya a utilizar en el MVP.

2024-09-19 19:02 UTC, octavio-delahoz-uninorte commented on src/components/Product/ProductCard/ProductCard.tsx
> +    <div className="bg-white shadow-sm rounded-md p-4 relative flex flex-col border border-neutral-300">
Otra cosa que olvidé comentar, donde está el link al PDP. Es decir no importa que apunte a Home por el momento.

2024-09-19 19:03 UTC, octavio-delahoz-uninorte commented on src/data/FeaturedProducts.ts
> +export const FeaturedProducts: Product[] = [
Donde manejarían la url que apunta al PDP ? Por el momento aclaro que sería "/"

2024-09-20 20:20 UTC, Sonya-c commented on src/components/Product/ProductCard/ProductCard.tsx
> +  }
Esto de aca podrías moverlo a utils?

2024-09-20 20:20 UTC, Sonya-c commented on src/components/Product/ProductCard/ProductCard.tsx
> +  }
Also, recuerda que el discount es un campo opcional

2024-09-20 20:20 UTC, Sonya-c commented on src/pages/HomePage.tsx
> +        <FeaturedProductView></FeaturedProductView>
Cuando no tiene hijos puedes hacer 
```suggestion
        <FeaturedProductView />
```

2024-09-20 20:21 UTC, Sonya-c commented on src/components/Product/ProductCard/ProductCard.tsx
> +        <p className={`${product.discount ? 'line-through text-[#c6cacd]' : ''}`}>{priceFormatter(product.price)}</p>
Sabes, este color es algo dificil de ver

2024-09-21 21:51 UTC, Orun1tia commented on src/pages/HomePage.tsx
>          <h1>Home Page</h1>
Hay que eliminar este texto

2024-09-22 22:11 UTC, Orun1tia approved these changes

2024-09-22 23:47 UTC, EmilyRoldan commented
puedes agregar un espacio entre el featured products y las cartas  y puedes cambiar el titulo a Best selling products o algo parecido. 
![image](https://github.com/user-attachments/assets/97c7087c-b749-4b0e-bffd-dd1b539070e6)

2024-09-23 01:07 UTC, Sonya-c requested changes

2024-09-23 01:07 UTC, Sonya-c commented on src/components/Breadcumb/Breadcumb.tsx
> +                <span>{capitalize(value)}</span>
Puede utilizar la clase de tailwind

2024-09-23 01:07 UTC, Sonya-c commented on src/components/Breadcumb/Breadcumb.tsx
> +        )}
Sabes, creo qeu el link al home no es tan necesario

2024-09-23 01:07 UTC, Sonya-c commented on src/components/Breadcumb/Breadcumb.tsx
> +  // Divide la ruta en segmentos para formar el breadcrumb
In english, pls

2024-09-23 01:07 UTC, Sonya-c commented on src/components/Breadcumb/Breadcumb.tsx
> +  const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
Este tipo de funciones debería esta en el utils. De todas formas, sería mejor utilizar la clase capitalize de tailwind

2024-09-23 01:07 UTC, Sonya-c commented on src/data/FeaturedProducts.ts
Este archivo ya tendría que se eliminado

2024-09-23 01:07 UTC, Sonya-c commented on src/layouts/BaseLayout.tsx
> +      <Breadcumb/>
No todas las paginas requiren utilizar el breadcumb

2024-09-23 01:07 UTC, Sonya-c commented on src/components/Product/FeaturedProductView/FeaturedProductView.tsx
> +    .slice(0, 12); // Tomar los primeros 12
In English please

2024-09-23 01:07 UTC, Sonya-c commented on src/utils/functions.ts
> +}
Podrías documentar estas funciones utilizado jsdoc


```suggestion
/**
 * This function bla, bla, bla
 * @param {number} price - default Price 
 * @return {string} - formated price
 */
export function priceFormatter(price: number): string {
  return price.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}
```

2024-09-23 01:07 UTC, Sonya-c commented on src/utils/functions.ts
> +
Esta tambien 


```suggestion
/**
 * This function bla, bla, bla
 * @param {number} price - Original price
 * @param {number} discount - Discount 
 * @return {number} - Discounted price
 */
export function getDiscountedPrice(price: number, discount: number): number {
  return price - (price * discount);
}
```

Also, podrías hacer discount un parametro opcional?

2024-09-23 01:07 UTC, Sonya-c commented on src/components/Breadcumb/index.ts
> +export default Breadcumb;
```suggestion
import Breadcrumb from "./Breadcumb";

export default Breadcrumb;
```

2024-09-23 01:20 UTC, daolivaress commented on src/components/Breadcumb/Breadcumb.tsx
> +        )}
quito el link pero dejo el home, como para que quede bien la ruta del breadcumb

2024-09-23 01:30 UTC, daolivaress commented on src/utils/functions.ts
> +
es que esa función solo se ejecuta si el producto tiene discount, eso lo tengo en product card por eso no lo puse como parámetro opcional

2024-09-23 02:26 UTC, Sonya-c requested changes
![image](https://github.com/user-attachments/assets/4820b8e5-67ec-4930-b343-2e9b828e6f7c)

- Podrías añadir un espacio entre los productos y el banner de abajo
- Also, metele un max width al los productos
- Es posible que sean menos? como 5
- Creo que no estan del todo centrado
-  
![image](https://github.com/user-attachments/assets/ffa93394-c767-44ae-89bc-9e2a882a7891)

2024-09-23 03:59 UTC, EmilyRoldan approved these changes

2024-09-23 04:10 UTC, Sonya-c approved these changes

2024-09-23 04:15 UTC, merged