V1.4
dr-von-doom/exclusive pull request #16
Opened 2024-09-21 07:51 UTC by Orun1tia

Header finished

2024-09-21 23:31 UTC, Sonya-c approved these changes

2024-09-22 04:39 UTC, EmilyRoldan approved these changes
well done

2024-09-22 04:49 UTC, EmilyRoldan requested changes
use font family: poppins pls

2024-09-22 05:40 UTC, EmilyRoldan approved these changes

2024-09-22 05:59 UTC, merged