Fix/hu2007 subheader padding
dr-von-doom/exclusive pull request #29
Opened 2024-09-22 22:02 UTC by Orun1tia

2024-09-22 22:11 UTC, EmilyRoldan approved these changes
muy dindo! seguiste todas las sugerencias a la perfeccion

2024-09-23 01:16 UTC, Sonya-c requested changes

2024-09-23 01:16 UTC, Sonya-c commented on src/components/Header/Header.tsx
>          </button>
A estos dos elementos, creo que podrías aumentarle el px-5 
```suggestion
        <input
          className="focus:outline-none rounded-l p-3 px-5 w-full bg-[#F5F5F5] border-none"
          type="text"
          placeholder="What are you looking for?"
        />
        <button className="rounded-r p-2 px-5 bg-[#F5F5F5] border-none cursor-pointer">
          <img className="h-5 w-5" src={searchIcon} alt="search" />
        </button>
```

2024-09-23 01:17 UTC, Sonya-c approved these changes

2024-09-23 01:21 UTC, merged