feat(HU2017): completed
dr-von-doom/exclusive pull request #55
Opened 2024-09-30 07:53 UTC by EmilyRoldan

2024-10-02 03:56 UTC, Sonya-c requested changes

2024-10-02 03:56 UTC, Sonya-c commented on public/assets/images/ads/ad-home.svg
Por favor, dejen de llamar esto ads :'c. Algunos navegadores bloquean este contenido porque piensa que son anuncios. Llamalo promotional image o algo por el estilo

2024-10-02 03:56 UTC, Sonya-c commented on src/services/promotionalImage.ts
> +export const getPromotionalImagesFromApi = async (): Promise<
`getPromotionalImages` esta bien, no tienes que decir 'fromApi'

2024-10-02 03:56 UTC, Sonya-c commented on src/services/promotionalImage.ts
> +};
mm, no. Si estoy lo vas a usar también en el componente, es mejor que lo muevas a types. Y en lugar de `PromotionalImageProps` creo que quedaría mejor `PromotionalImageData`

2024-10-02 03:56 UTC, Sonya-c commented on src/pages/HomePage.tsx
> +            <p>No hay imágenes promocionales disponibles.</p>
En ingles

2024-10-02 03:56 UTC, Sonya-c commented on src/Hooks/usePromotionalImages.ts
> +import { getPromotionalImagesFromApi } from "@/services/promotionalImage.ts"; // Asegúrate de que la ruta sea correcta
Puedes quitar esto

2024-10-02 03:56 UTC, Sonya-c commented on src/pages/HomePage.tsx
> +    isLoading,
Ya que esto esta en el home, y que va a haber otros llamados a apis, creo que sería buena idea que tambien renombres error (promotionalImagesError) y isLoading (isLoadingError)

2024-10-02 03:56 UTC, Sonya-c commented on src/pages/HomePage.tsx
> +            <p>No hay imágenes promocionales disponibles.</p>
Esta parte es mas compleja, creo qeu deberías manejar la logica de error, cargado dentro del componente y Loading. Y en el caso del error, tal vez crear un componente global

2024-10-04 13:42 UTC, Sonya-c commented
![image](https://github.com/user-attachments/assets/5175a3c4-d889-4e30-83cd-fd488c6fb3dc)

Podrías hacer que los skeletons tenga el tamaño que tendrían sus imagenes reales?

2024-10-04 13:42 UTC, Sonya-c approved these changes

2024-10-04 19:16 UTC, Sonya-c approved these changes

2024-10-04 19:18 UTC, DarioMejia approved these changes
Well done.

2024-10-04 19:30 UTC, merged