Feature/hu2026 shopping cart breadcrumb
dr-von-doom/exclusive pull request #59
Opened 2024-10-02 13:49 UTC by daolivaress

2024-10-04 14:12 UTC, Sonya-c requested changes
Un par de sugerencias 

- Este select podrías hacerlo mas bonito?
![image](https://github.com/user-attachments/assets/11514763-4bf9-41f3-9132-9f9991d31962)

Fijate como esta en el PLP

![image](https://github.com/user-attachments/assets/25e96d42-f8bb-41d9-93f9-7afb60132348)
 
 - PurchaseSummary podría tener un borde mas gris
![image](https://github.com/user-attachments/assets/487cd96a-3523-4725-8ebe-098ef1ce6e20)

- Also, podrías hacer el diseño de esto

![image](https://github.com/user-attachments/assets/45a87a5c-db4c-4c24-a0ea-ea53b4312c6b)

mas similar a esto

![image](https://github.com/user-attachments/assets/4b5ec46b-8560-4f9c-9db0-1403b40c73f2)

2024-10-04 14:12 UTC, Sonya-c commented on src/components/CartProduct/CartProduct.tsx
> +export const CartProduct = ({ product }: any) => {
```suggestion
export const CartProduct = ({ product }: Product) => {
```

2024-10-04 14:12 UTC, Sonya-c commented on src/components/CartProduct/CartProduct.tsx
> +          <p className="font-semibold">{priceFormatter(product.price)}</p>
debes aplicar el descuento. Hay una función en utils que hace eso

2024-10-04 14:12 UTC, Sonya-c commented on src/pages/Shopping-cart/ShoppingCartPage.tsx
> +        <PurchaseSummary></PurchaseSummary>
```suggestion
        <PurchaseSummary />
```

2024-10-04 14:12 UTC, Sonya-c commented on src/pages/Shopping-cart/ShoppingCartPage.tsx
> +      <Breadcrumb></Breadcrumb>
```suggestion
      <Breadcrumb />
```

2024-10-04 14:12 UTC, Sonya-c commented on src/components/common/Header/Header.tsx
> +export const Header = ({ logoLink = "/", cartLink = "/cart" }: HeaderProps) => {
Por que estos son props del header?

2024-10-04 14:12 UTC, Sonya-c commented on src/components/PurchaseSummary/PurchaseSummary.tsx
> +};
No debería recibir esto la lista de products y calcular esto?

2024-10-04 14:14 UTC, Sonya-c commented
Also, esta tarea no era para añadir el breadcrum no mas? por que esta todo lo del carrito aquí?

2024-10-04 16:16 UTC, daolivaress commented on src/components/common/Header/Header.tsx
> +export const Header = ({ logoLink = "/", cartLink = "/cart" }: HeaderProps) => {
Eso ya estaba así desde antes, lo único que agregue yo fue el link del carrito

2024-10-04 22:23 UTC, EmilyRoldan approved these changes

2024-10-05 02:47 UTC, Sonya-c commented on src/router.tsx
> +  {
Ponlo antes de NotFound

2024-10-05 02:47 UTC, Sonya-c commented on src/components/common/Header/Header.tsx
> +export const Header = ({ logoLink = "/", cartLink = "/cart" }: HeaderProps) => {
okay

2024-10-05 02:48 UTC, Sonya-c approved these changes

2024-10-05 02:59 UTC, merged